package com.example;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import com.mysql.cj.x.protobuf.MysqlxNotice.Frame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class addVehicle extends javax.swing.JFrame {

    /**
     * Creates new form Vehicle
     */
    public int CustomerID;
    public addVehicle(int CustomerID) {
        this.CustomerID = CustomerID;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Company_l = new javax.swing.JLabel();
        Model_l = new javax.swing.JLabel();
        Year_l = new javax.swing.JLabel();
        Owner_name_l = new javax.swing.JLabel();
        Registration_number_l = new javax.swing.JLabel();
        Vehicle_category_l = new javax.swing.JLabel();
        Color_l = new javax.swing.JLabel();
        Registration_number = new javax.swing.JTextField();
        Company = new javax.swing.JTextField();
        Model = new javax.swing.JTextField();
        Owner_name = new javax.swing.JTextField();
        Color = new javax.swing.JTextField();
        Vehicle_category = new javax.swing.JTextField();
        Add_another_vehicle = new javax.swing.JButton();
        Skip_and_continue = new javax.swing.JButton();
        year = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Company.setEditable(false);
        Model.setEditable(false);
        Owner_name.setEditable(false);
        Color.setEditable(false);
        Vehicle_category.setEditable(false);
        year.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("VEHICLE DETAILS");

        Company_l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Company_l.setForeground(new java.awt.Color(0, 51, 255));
        Company_l.setText("Company");

        Model_l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Model_l.setForeground(new java.awt.Color(0, 51, 255));
        Model_l.setText("Model");

        Year_l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Year_l.setForeground(new java.awt.Color(0, 51, 255));
        Year_l.setText("Year");

        Owner_name_l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Owner_name_l.setForeground(new java.awt.Color(0, 51, 255));
        Owner_name_l.setText("Owner Name");

        Registration_number_l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Registration_number_l.setForeground(new java.awt.Color(0, 51, 255));
        Registration_number_l.setText("Registration number");
        Registration_number.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
            }

            @Override
            public void focusLost(FocusEvent e) {
                    displayDetails(Registration_number.getText());
            }
        });

        Vehicle_category_l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Vehicle_category_l.setForeground(new java.awt.Color(0, 51, 255));
        Vehicle_category_l.setText("Vehicle category");

        Color_l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Color_l.setForeground(new java.awt.Color(0, 51, 255));
        Color_l.setText("Color");

        // Vehicle_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose vehicle", "Bike", "Car", "Truck", "Van", "Bus", "SUV (Sports Utility Vehicle)", "RV (Recreational Vehicle)", "Pickup Truck", "Electric Vehicle (EV)", "Hybrid Vehicle" }));

        Add_another_vehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Add_another_vehicle.setForeground(new java.awt.Color(0, 51, 255));
        Add_another_vehicle.setText("Add Another Vehicle");
        Add_another_vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_another_vehicleActionPerformed(evt);
            }
        });

        Skip_and_continue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Skip_and_continue.setForeground(new java.awt.Color(0, 51, 255));
        Skip_and_continue.setText("Skip and Continue");
        Skip_and_continue.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent arg0) {
                Skip_and_continueActionPerformed();

        }});
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Registration_number_l, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Company_l, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Model_l, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year_l, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Owner_name_l, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Color_l, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vehicle_category_l, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Add_another_vehicle)
                        .addGap(97, 97, 97)
                        .addComponent(Skip_and_continue))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Color, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Registration_number, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Company, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Model, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Owner_name, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Vehicle_category, javax.swing.GroupLayout.Alignment.LEADING, 0, 244, Short.MAX_VALUE)
                        .addComponent(year, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registration_number_l, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registration_number, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Company_l, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Company, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Model_l, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Model, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Year_l, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Owner_name_l, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Owner_name, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Color_l, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vehicle_category_l, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vehicle_category, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_another_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Skip_and_continue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        
    private boolean Skip_and_continueActionPerformed(){
        new UserHomePage(this.CustomerID).setVisible(true);
        this.setVisible(false);
        return true;
    }
    private void Add_another_vehicleActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        if(StoreVehicle(Registration_number.getText())){
            JOptionPane.showMessageDialog(this, "Vehicle added successfully");
            Registration_number.setText("");
            Company.setText("");
            Model.setText("");
            Owner_name.setText("");
            Color.setText("");
            Vehicle_category.setText("");
            year.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Vehicle already exists","Error",JOptionPane.ERROR_MESSAGE);
            Registration_number.setText("");
            Company.setText("");
            Model.setText("");
            Owner_name.setText("");
            Color.setText("");
            Vehicle_category.setText("");
            year.setText("");
        }

    } 
    
    private void displayDetails(String reg_num){
        try(Connection conn = DBConnector.getConnection()){
            String query = "SELECT * FROM RC_Details WHERE registration_number = ?;";
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, reg_num);
            result = statement.executeQuery();

            if(result.next()){
                Company.setText(result.getString("make"));
                Model.setText(result.getString("model"));
                Owner_name.setText(result.getString("owner_name"));
                Color.setText(result.getString("color"));
                Vehicle_category.setText(result.getString("vehicle_category"));
                year.setText(result.getString("year"));
            } else {
                JOptionPane.showMessageDialog(this, "Enter valid registration number","ERROR",JOptionPane.ERROR_MESSAGE);
                Registration_number.setText("");

            }

        } catch(SQLException ex){
            ex.printStackTrace();
        }
    }
    private boolean StoreVehicle(String reg_num){
        try(Connection conn = DBConnector.getConnection()){
            String query = "INSERT INTO Vehicle_Details VALUES(?,?,?,?,?,?,?,?,?,?,?);";
            PreparedStatement statement = conn.prepareStatement(query);
            
            PreparedStatement statement2 = conn.prepareStatement("SELECT * FROM RC_Details WHERE registration_number = ?;");
            statement2.setString(1, reg_num);
            System.out.println(reg_num);
            result = statement2.executeQuery();
            result.next();
            statement.setInt(1, CustomerID);
            statement.setString(2, result.getString("registration_number"));
            statement.setString(3, result.getString("make"));
            statement.setString(4, result.getString("model"));
            statement.setString(5, result.getString("year"));
            statement.setString(6, result.getString("owner_name"));
            statement.setString(7, result.getString("color"));
            statement.setString(8, result.getString("vehicle_category"));
            statement.setString(9, result.getString("cc"));
            statement.setString(10, result.getString("engine_chase_number"));
            statement.setString(11, result.getString("fitness_upto_date"));
            

            statement.executeUpdate();
            return true;
        }catch (SQLException ex){
            ex.printStackTrace();
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addVehicle(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Add_another_vehicle;
    private javax.swing.JTextField Color;
    private javax.swing.JLabel Color_l;
    private javax.swing.JTextField Company;
    private javax.swing.JLabel Company_l;
    private javax.swing.JTextField Model;
    private javax.swing.JLabel Model_l;
    private javax.swing.JTextField Owner_name;
    private javax.swing.JLabel Owner_name_l;
    private javax.swing.JTextField Registration_number;
    private javax.swing.JLabel Registration_number_l;
    private javax.swing.JButton Skip_and_continue;
    private javax.swing.JTextField Vehicle_category;
    private javax.swing.JLabel Vehicle_category_l;
    private javax.swing.JLabel Year_l;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField year;
    private static ResultSet result;
    // End of variables declaration                   
}
