package com.example;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class AdminAddPolicy extends javax.swing.JFrame {

    /**
     * Creates new form Add_policy
     */
    public AdminAddPolicy() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        provider_l = new javax.swing.JLabel();
        vehicle_type_l = new javax.swing.JLabel();
        claim_settled_l = new javax.swing.JLabel();
        policy_name_l = new javax.swing.JLabel();
        highlights_l = new javax.swing.JLabel();
        policy_duration_l = new javax.swing.JLabel();
        exclusions_l = new javax.swing.JLabel();
        claim_procedure_l = new javax.swing.JLabel();
        policy_name = new javax.swing.JTextField();
        provider = new javax.swing.JTextField();
        vehicle_type = new javax.swing.JComboBox<>();
        claim_settled = new javax.swing.JTextField();
        policy_duration = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        exclusions = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        highlights = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        claim_procedure = new javax.swing.JTextArea();
        Button = new javax.swing.JButton();
        add_policy = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        provider_l.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        provider_l.setText("Provider");

        vehicle_type_l.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vehicle_type_l.setText("Vehicle Type");

        claim_settled_l.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        claim_settled_l.setText("Claim settled");

        policy_name_l.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        policy_name_l.setText("Policy name");

        highlights_l.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        highlights_l.setText("Highlights");

        policy_duration_l.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        policy_duration_l.setText("Policy Duration");

        exclusions_l.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exclusions_l.setText("Exclusions");

        claim_procedure_l.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        claim_procedure_l.setText("Claim Procedure");

        vehicle_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose vehicle", "Car", "Bike" }));
        vehicle_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicle_typeActionPerformed(evt);
            }
        });

        policy_duration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose policy duration", "6", "12" }));
        policy_duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policy_durationActionPerformed(evt);
            }
        });

        exclusions.setColumns(20);
        exclusions.setRows(5);
        jScrollPane1.setViewportView(exclusions);

        highlights.setColumns(20);
        highlights.setRows(5);
        jScrollPane2.setViewportView(highlights);

        claim_procedure.setColumns(20);
        claim_procedure.setRows(5);
        jScrollPane3.setViewportView(claim_procedure);

        Button.setBackground(new java.awt.Color(0, 0, 0));
        Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button.setForeground(new java.awt.Color(255, 255, 255));
        Button.setText("SUBMIT");
        Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonMouseExited(evt);
            }
        });
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        add_policy.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        add_policy.setForeground(new java.awt.Color(0, 51, 255));
        add_policy.setText("                      ADD POLICY");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previouspage.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(provider_l, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(provider, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(claim_settled, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(policy_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehicle_type, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(vehicle_type_l, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(exclusions_l, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(claim_procedure_l, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(policy_name_l, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(policy_name, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(claim_settled_l, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(policy_duration_l, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addComponent(highlights_l, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(back)
                                .addGap(189, 189, 189)
                                .addComponent(add_policy, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(370, 370, 370))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_policy, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(policy_name_l, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(policy_name, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(highlights_l, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(provider_l, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(provider, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(claim_settled_l, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(claim_settled, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exclusions_l, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(policy_duration_l, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(policy_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vehicle_type, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vehicle_type_l)
                                .addComponent(claim_procedure_l, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void policy_durationActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // JOptionPane.showMessageDialog(this, highlights.getText()); 
        if(policy_name.getText().isEmpty() || provider.getText().isEmpty() ||claim_settled.getText().isEmpty() ||highlights.getText().isEmpty() ||exclusions.getText().isEmpty() ||claim_procedure.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Fill all the details","Data invalid",JOptionPane.ERROR_MESSAGE);
            policy_name.setText("");
            provider.setText("");
            claim_settled.setText("");
            highlights.setText("");
            exclusions.setText("");
            claim_procedure.setText("");
        }

        String values[] = {
            policy_name.getText(),
            provider.getText(),
            (String) vehicle_type.getSelectedItem(),
            claim_settled.getText(),
            (String) policy_duration.getSelectedItem(),
            highlights.getText(),
            exclusions.getText(),
            claim_procedure.getText()
        };

        if(StorePolicy(values)){
            JOptionPane.showMessageDialog(this, "New Policy added successfully!","SuccessMessage",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error in storing Policy","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }     
    private boolean StorePolicy(String values[]){
        try(Connection conn = DBConnector.getConnection()){
            String query = "INSERT INTO List_of_Policies(PolicyName,Provider,VehicleType,ClaimsSettled,PolicyDuration,Highlights,Exclusions,ClaimProcedure) VALUES(?,?,?,?,?,?,?,?)";
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setString(1, values[0]);
            statement.setString(2, values[1]);
            statement.setString(3, values[2]);
            statement.setString(4, values[3]);
            statement.setString(5, values[4]);
            statement.setString(6, values[5]);
            statement.setString(7, values[6]);
            statement.setString(8, values[7]);

            int rowsInserted = statement.executeUpdate();
            if(rowsInserted > 0){
                return true;
            } else {
                return false;
            }

        } catch (SQLException ex){
            ex.printStackTrace();
            return false;
        }
    }                                      

    private void ButtonMouseEntered(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        Button.setBackground(new java.awt.Color(0, 204, 0));
        Button.setForeground(new java.awt.Color(0, 0, 0));
    }                                   

    private void ButtonMouseExited(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
        Button.setBackground(new java.awt.Color(0, 51, 255));
        Button.setForeground(new java.awt.Color(255, 255, 255));
    }                                  

    private void vehicle_typeActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void backMouseClicked(java.awt.event.MouseEvent evt) {                                  
        this.setVisible(false);
        new AdminHomePage().setVisible(true);
    }                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddPolicy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Button;
    private javax.swing.JLabel add_policy;
    private javax.swing.JLabel back;
    private javax.swing.JTextArea claim_procedure;
    private javax.swing.JLabel claim_procedure_l;
    private javax.swing.JTextField claim_settled;
    private javax.swing.JLabel claim_settled_l;
    private javax.swing.JTextArea exclusions;
    private javax.swing.JLabel exclusions_l;
    private javax.swing.JTextArea highlights;
    private javax.swing.JLabel highlights_l;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> policy_duration;
    private javax.swing.JLabel policy_duration_l;
    private javax.swing.JTextField policy_name;
    private javax.swing.JLabel policy_name_l;
    private javax.swing.JTextField provider;
    private javax.swing.JLabel provider_l;
    private javax.swing.JComboBox<String> vehicle_type;
    private javax.swing.JLabel vehicle_type_l;
    // End of variables declaration                   
}