package com.example;

//package com.project1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vivek
 */

 import javax.swing.*;
 import javax.swing.border.Border;
 import java.awt.*;
 import java.sql.Connection;
 
 public class checkout extends javax.swing.JFrame {
 
     /**
      * Creates new form checkout
      */
     public checkout() {
         initComponents();
         this.setResizable(false);
         this.setLocationRelativeTo(null);
         this.setSize(900,550);
     }
 
     /**
      * This method is called from within the constructor to initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
     private void initComponents() {
 
         jPanel1 = new javax.swing.JPanel();
         back_Button = new javax.swing.JButton();
         payment_label = new javax.swing.JLabel();
         jPanel2 = new javax.swing.JPanel();
         select_payment_method_label = new javax.swing.JLabel();
         card_Panel = new javax.swing.JPanel();
         card_image_label = new javax.swing.JLabel();
         card_Label = new javax.swing.JLabel();
         jPanel4 = new javax.swing.JPanel();
         UPI_Panel = new javax.swing.JPanel();
         upi_image_label = new javax.swing.JLabel();
         UPI_Label = new javax.swing.JLabel();
         upi_card_no_panel = new javax.swing.JPanel();
         set_upicard_label = new javax.swing.JLabel();
         upi_card_no_input_textfield = new javax.swing.JTextField();
         cvv_exp_panel = new javax.swing.JPanel();
         CVV_label = new javax.swing.JLabel();
         cvv_textfield = new javax.swing.JTextField();
         Expiry_date_label = new javax.swing.JLabel();
         expirymonth_label = new javax.swing.JTextField();
         expiryyear_textfield = new javax.swing.JTextField();
         M_expirymonth_label = new javax.swing.JLabel();
         Y_expiryyear_label = new javax.swing.JLabel();
         make_payment_panel = new javax.swing.JPanel();
         make_payment_Button = new javax.swing.JButton();
 
         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
         upi_card_no_panel.setVisible(false);
         cvv_exp_panel.setVisible(false);
         make_payment_panel.setVisible(false);

         back_Button.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
         back_Button.setForeground(new java.awt.Color(255, 255, 255));
         //back_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previouspage.png"))); // NOI18N
         back_Button.setText(" ");
         back_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previouspage.png")));
         back_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
         back_Button.setOpaque(true);
         back_Button.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 back_ButtonActionPerformed(evt);
             }
         });
 
         payment_label.setFont(new java.awt.Font("Optima", 1, 40)); // NOI18N
         payment_label.setForeground(new java.awt.Color(24, 116, 227));
         payment_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
         payment_label.setText("Payment");
 
         javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
         jPanel1.setLayout(jPanel1Layout);
         jPanel1Layout.setHorizontalGroup(
             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel1Layout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(back_Button)
                 .addGap(192, 192, 192)
                 .addComponent(payment_label, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(244, Short.MAX_VALUE))
         );
         jPanel1Layout.setVerticalGroup(
             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel1Layout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(back_Button)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addGroup(jPanel1Layout.createSequentialGroup()
                 .addComponent(payment_label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGap(0, 20, Short.MAX_VALUE))
         );
 
         select_payment_method_label.setFont(new java.awt.Font("Gurmukhi MT", 1, 18)); // NOI18N
         select_payment_method_label.setText("Select a payment method:");
 
         card_Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
         card_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
             public void mouseClicked(java.awt.event.MouseEvent evt) {
                 card_PanelMouseClicked(evt);
             }
             public void mouseEntered(java.awt.event.MouseEvent evt) {
                 card_PanelMouseEntered(evt);
             }
             public void mouseExited(java.awt.event.MouseEvent evt) {
                 card_PanelMouseExited(evt);
             }
         });

         upi_card_no_input_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                upi_card_no_input_textfieldFocusLost(evt);
            }
        });

        cvv_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cvv_textfieldFocusLost(evt);
            }
        });

        expirymonth_label.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                expirymonth_labelFocusLost(evt);
            }
        });

        expiryyear_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                expiryyear_textfieldFocusLost(evt);
            }
        });
 
         //card_image_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/debit-card.png"))); // NOI18N
         card_image_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/debit-card.png")));
 
         card_Label.setText("Card");

 
         javax.swing.GroupLayout card_PanelLayout = new javax.swing.GroupLayout(card_Panel);
         card_Panel.setLayout(card_PanelLayout);
         card_PanelLayout.setHorizontalGroup(
             card_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(card_PanelLayout.createSequentialGroup()
                 .addGroup(card_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(card_PanelLayout.createSequentialGroup()
                         .addGap(21, 21, 21)
                         .addComponent(card_image_label))
                     .addGroup(card_PanelLayout.createSequentialGroup()
                         .addGap(35, 35, 35)
                         .addComponent(card_Label)))
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
         card_PanelLayout.setVerticalGroup(
             card_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(card_PanelLayout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(card_image_label)
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addComponent(card_Label)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
 
         javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
         jPanel4.setLayout(jPanel4Layout);
         jPanel4Layout.setHorizontalGroup(
             jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGap(0, 105, Short.MAX_VALUE)
         );
         jPanel4Layout.setVerticalGroup(
             jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGap(0, 138, Short.MAX_VALUE)
         );
 
         UPI_Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
         UPI_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
             public void mouseClicked(java.awt.event.MouseEvent evt) {
                 UPI_PanelMouseClicked(evt);
             }
             public void mouseEntered(java.awt.event.MouseEvent evt) {
                 UPI_PanelMouseEntered(evt);
             }
             public void mouseExited(java.awt.event.MouseEvent evt) {
                 UPI_PanelMouseExited(evt);
             }
         });
 
         //upi_image_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upi_logo.png"))); // NOI18N
         upi_image_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upi_logo.png")));
 
         UPI_Label.setText("UPI");
         
         javax.swing.GroupLayout UPI_PanelLayout = new javax.swing.GroupLayout(UPI_Panel);
         UPI_Panel.setLayout(UPI_PanelLayout);
         UPI_PanelLayout.setHorizontalGroup(
             UPI_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(UPI_PanelLayout.createSequentialGroup()
                 .addGap(21, 21, 21)
                 .addComponent(upi_image_label)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UPI_PanelLayout.createSequentialGroup()
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addComponent(UPI_Label)
                 .addGap(39, 39, 39))
         );
         UPI_PanelLayout.setVerticalGroup(
             UPI_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(UPI_PanelLayout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(upi_image_label)
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                 .addComponent(UPI_Label)
                 .addContainerGap(18, Short.MAX_VALUE))
         );
 
         javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
         jPanel2.setLayout(jPanel2Layout);
         jPanel2Layout.setHorizontalGroup(
             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel2Layout.createSequentialGroup()
                 .addGap(28, 28, 28)
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel2Layout.createSequentialGroup()
                         .addComponent(UPI_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                         .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(card_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(select_payment_method_label))
                 .addContainerGap(27, Short.MAX_VALUE))
         );
         jPanel2Layout.setVerticalGroup(
             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel2Layout.createSequentialGroup()
                 .addGap(23, 23, 23)
                 .addComponent(select_payment_method_label)
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                 .addComponent(card_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel2Layout.createSequentialGroup()
                         .addGap(43, 43, 43)
                         .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel2Layout.createSequentialGroup()
                         .addGap(18, 18, 18)
                         .addComponent(UPI_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                 .addContainerGap(37, Short.MAX_VALUE))
         );
 
         set_upicard_label.setText(" ");
 
         upi_card_no_input_textfield.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 upi_card_no_input_textfieldActionPerformed(evt);
             }
         });
 
         javax.swing.GroupLayout upi_card_no_panelLayout = new javax.swing.GroupLayout(upi_card_no_panel);
         upi_card_no_panel.setLayout(upi_card_no_panelLayout);
         upi_card_no_panelLayout.setHorizontalGroup(
             upi_card_no_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(upi_card_no_panelLayout.createSequentialGroup()
                 .addGap(21, 21, 21)
                 .addComponent(set_upicard_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGap(18, 18, 18)
                 .addComponent(upi_card_no_input_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(39, Short.MAX_VALUE))
         );
         upi_card_no_panelLayout.setVerticalGroup(
             upi_card_no_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upi_card_no_panelLayout.createSequentialGroup()
                 .addContainerGap(39, Short.MAX_VALUE)
                 .addGroup(upi_card_no_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(set_upicard_label)
                     .addComponent(upi_card_no_input_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addGap(29, 29, 29))
         );
 
         CVV_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
         CVV_label.setText("Enter CVV:");
 
         cvv_textfield.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 cvv_textfieldActionPerformed(evt);
             }
         });
 
         Expiry_date_label.setText("Expiry Date:");
 
         expirymonth_label.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 expirymonth_labelActionPerformed(evt);
             }
         });
 
         M_expirymonth_label.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
         M_expirymonth_label.setText("M");
 
         Y_expiryyear_label.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
         Y_expiryyear_label.setText("Y");
 
         javax.swing.GroupLayout cvv_exp_panelLayout = new javax.swing.GroupLayout(cvv_exp_panel);
         cvv_exp_panel.setLayout(cvv_exp_panelLayout);
         cvv_exp_panelLayout.setHorizontalGroup(
             cvv_exp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cvv_exp_panelLayout.createSequentialGroup()
                 .addGroup(cvv_exp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(cvv_exp_panelLayout.createSequentialGroup()
                         .addGap(14, 14, 14)
                         .addComponent(CVV_label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                         .addComponent(cvv_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(Expiry_date_label)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                         .addComponent(expirymonth_label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cvv_exp_panelLayout.createSequentialGroup()
                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(M_expirymonth_label)
                         .addGap(21, 21, 21)))
                 .addGroup(cvv_exp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(expiryyear_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cvv_exp_panelLayout.createSequentialGroup()
                         .addComponent(Y_expiryyear_label)
                         .addGap(20, 20, 20)))
                 .addGap(19, 19, 19))
         );
         cvv_exp_panelLayout.setVerticalGroup(
             cvv_exp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(cvv_exp_panelLayout.createSequentialGroup()
                 .addGap(16, 16, 16)
                 .addGroup(cvv_exp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(M_expirymonth_label)
                     .addComponent(Y_expiryyear_label))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addGroup(cvv_exp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(CVV_label)
                     .addComponent(cvv_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(Expiry_date_label)
                     .addComponent(expirymonth_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(expiryyear_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addContainerGap(41, Short.MAX_VALUE))
         );
 
         make_payment_Button.setBackground(new java.awt.Color(0, 0, 0));
         make_payment_Button.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
         make_payment_Button.setForeground(new java.awt.Color(255, 255, 255));
         make_payment_Button.setText("Make Payment");
         make_payment_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
         make_payment_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
         make_payment_Button.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 make_payment_ButtonActionPerformed(evt);
             }
         });
 
         javax.swing.GroupLayout make_payment_panelLayout = new javax.swing.GroupLayout(make_payment_panel);
         make_payment_panel.setLayout(make_payment_panelLayout);
         make_payment_panelLayout.setHorizontalGroup(
             make_payment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, make_payment_panelLayout.createSequentialGroup()
                 .addContainerGap(26, Short.MAX_VALUE)
                 .addComponent(make_payment_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGap(19, 19, 19))
         );
         make_payment_panelLayout.setVerticalGroup(
             make_payment_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, make_payment_panelLayout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(make_payment_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                 .addContainerGap())
         );
 
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
         getContentPane().setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                         .addGap(25, 25, 25)
                         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                         .addGap(60, 60, 60)
                         .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(layout.createSequentialGroup()
                                 .addGap(27, 27, 27)
                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                     .addComponent(cvv_exp_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                     .addComponent(upi_card_no_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                             .addGroup(layout.createSequentialGroup()
                                 .addGap(113, 113, 113)
                                 .addComponent(make_payment_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                 .addContainerGap(34, Short.MAX_VALUE))
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                         .addGap(30, 30, 30)
                         .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                     .addGroup(layout.createSequentialGroup()
                         .addGap(89, 89, 89)
                         .addComponent(upi_card_no_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                         .addComponent(cvv_exp_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGap(18, 18, 18)
                         .addComponent(make_payment_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGap(0, 0, Short.MAX_VALUE))))
         );
 
         pack();
     }// </editor-fold>                        
 
     private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        JOptionPane.showMessageDialog(this, "Payment Quit");
        //homepage homePage = new homepage();
        //homePage.setVisible(true);

        this.setVisible(false);
     }                                           
 
     private void card_PanelMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // Increase the size of the icon
        card_Panel.setBorder(BorderFactory.createLineBorder(Color.black, 2));
        UPI_Panel.setBorder(null); // Remove border highlight from UPI_Panel
        upi_card_no_panel.setVisible(true);
        set_upicard_label.setText("Enter Card Number: ");
        cvv_exp_panel.setVisible(true);
        make_payment_panel.setVisible(true);
    } 

     private void card_PanelMouseEntered(java.awt.event.MouseEvent evt) {                                        
         // TODO add your handling code here:
     }                                       
 
     private void card_PanelMouseExited(java.awt.event.MouseEvent evt) {                                       
         // TODO add your handling code here:
     }                                      
 
     private void UPI_PanelMouseClicked(java.awt.event.MouseEvent evt) {                                       
        UPI_Panel.setBorder(BorderFactory.createLineBorder(Color.black, 2));
        card_Panel.setBorder(null); // Remove border highlight from card_Panel
        upi_card_no_panel.setVisible(true);
        set_upicard_label.setText("Enter UPI ID: ");
        cvv_exp_panel.setVisible(false);
        make_payment_panel.setVisible(true);
     }                                      
 
     private void UPI_PanelMouseEntered(java.awt.event.MouseEvent evt) {                                       
        //upi_image_label.setIcon(new ImageIcon(upi_image_label.getImage().getScaledInstance(upi_image_label.getIconWidth() + 20, upi_image_label.getIconHeight() + 20, Image.SCALE_DEFAULT))); // TODO add your handling code here:
     }                                      
 
     private void UPI_PanelMouseExited(java.awt.event.MouseEvent evt) {                                      
        //productImageLabel.setIcon(productImage); // Reset image size
     }                                     
 
     private void upi_card_no_input_textfieldActionPerformed(java.awt.event.ActionEvent evt) {                                                            
         // TODO add your handling code here:
     }                                                           
 
     private void cvv_textfieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        //try (Connection conn = DBConnector.getConnection()) {
            
     }                                             
 
     private void expirymonth_labelActionPerformed(java.awt.event.ActionEvent evt) {                                                  
         // TODO add your handling code here:
     }                                                 
 
     private void make_payment_ButtonActionPerformed(java.awt.event.ActionEvent evt) { 
        if(upi_card_no_input_textfield.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter Valid Details", "ERROR", JOptionPane.ERROR_MESSAGE);
        }  
        else{    
                                                        
            JOptionPane.showMessageDialog(this, "Payment Successful");// TODO add your handling code here:
            this.setVisible(false);
            new HomePage(0).setVisible(true);
        }
     }  
     
     private void upi_card_no_input_textfieldFocusLost(java.awt.event.FocusEvent evt) {                                                      
        // if(upi_card_no_input_textfield.getText().length()< 16 || upi_card_no_input_textfield.getText().length()> 19 ){
        //     JOptionPane.showMessageDialog(null, "Card number should be between 16 to 19 digits", "ERROR", JOptionPane.ERROR_MESSAGE);
        // }
    }

    private void cvv_textfieldFocusLost(java.awt.event.FocusEvent evt) {                                        
        if(cvv_textfield.getText().length()!=3 ){
            JOptionPane.showMessageDialog(null, "CVV should be 3 digits", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    } 

    private void expirymonth_labelFocusLost(java.awt.event.FocusEvent evt) {                                            
        if(Integer.parseInt(expirymonth_label.getText())>12 ){
            JOptionPane.showMessageDialog(null, "Wrong input", "ERROR", JOptionPane.ERROR_MESSAGE);
    } 
}                                          

    private void expiryyear_textfieldFocusLost(java.awt.event.FocusEvent evt) {                                               
        if(Integer.parseInt(expiryyear_textfield.getText())>29 ){
            JOptionPane.showMessageDialog(null, "Wrong input", "ERROR", JOptionPane.ERROR_MESSAGE);
    } 
}   
 
     /**
      * @param args the command line arguments
      */
     
 //    Border border = BorderFactory.createLineBorder(Color.BLACK, 2);
 //    card_Panel.setBorder(border);
     public static void main(String args[]) {
         /* Set the Nimbus look and feel */
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
         /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
          * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
          */
         try {
             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 if ("Nimbus".equals(info.getName())) {
                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
                     break;
                 }
             }
         } catch (ClassNotFoundException ex) {
             java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (InstantiationException ex) {
             java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (IllegalAccessException ex) {
             java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
             java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }
         //</editor-fold>
 
         /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                 new checkout().setVisible(true);
             }
         });
     }
 
     // Variables declaration - do not modify                     
     private javax.swing.JLabel CVV_label;
     private javax.swing.JLabel Expiry_date_label;
     private javax.swing.JLabel M_expirymonth_label;
     private javax.swing.JLabel UPI_Label;
     private javax.swing.JPanel UPI_Panel;
     private javax.swing.JLabel Y_expiryyear_label;
     private javax.swing.JButton back_Button;
     private javax.swing.JLabel card_Label;
     private javax.swing.JPanel card_Panel;
     private javax.swing.JLabel card_image_label;
     private javax.swing.JPanel cvv_exp_panel;
     private javax.swing.JTextField cvv_textfield;
     private javax.swing.JTextField expirymonth_label;
     private javax.swing.JTextField expiryyear_textfield;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel4;
     private javax.swing.JButton make_payment_Button;
     private javax.swing.JPanel make_payment_panel;
     private javax.swing.JLabel payment_label;
     private javax.swing.JLabel select_payment_method_label;
     private javax.swing.JLabel set_upicard_label;
     private javax.swing.JTextField upi_card_no_input_textfield;
     private javax.swing.JPanel upi_card_no_panel;
     private javax.swing.JLabel upi_image_label;
     // End of variables declaration                   
 }