package com.example;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class ClaimPolicy extends javax.swing.JFrame {

    /**
     * Creates new form claim_policy_for_vehicle
     */    
    int CustomerID;
    String VehicleNumber;
    public ClaimPolicy(int CustomerID,String VehicleNUmber) {
        initComponents();
        this.setResizable(false);
        this.CustomerID = CustomerID;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CLAIMS_l = new javax.swing.JLabel();
        Incident_details_l = new javax.swing.JLabel();
        Date_and_time_l = new javax.swing.JLabel();
        Description_i_l = new javax.swing.JLabel();
        Location_l = new javax.swing.JLabel();
        CLAIM_DETAILS_L = new javax.swing.JLabel();
        Type_of_claim_l = new javax.swing.JLabel();
        Additionnal_comments_l = new javax.swing.JLabel();
        CANCEL = new java.awt.Button();
        SUBMIT = new java.awt.Button();
        jScrollPane5 = new javax.swing.JScrollPane();
        Additionnal_comments = new javax.swing.JTextArea();
        Type_of_claim = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Description_i = new javax.swing.JTextArea();
        Date_and_time = new com.toedter.calendar.JDateChooser();
        Location = new javax.swing.JComboBox<>();
        FIR_number = new javax.swing.JTextField();
        FIR_number_l1 = new javax.swing.JLabel();
        verify = new javax.swing.JButton();
        back_button_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CLAIMS_l.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        CLAIMS_l.setForeground(new java.awt.Color(0, 51, 255));
        CLAIMS_l.setText(" CLAIM POLICY FOR VEHICLE ");

        Incident_details_l.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Incident_details_l.setText("Incident details   :");

        Date_and_time_l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Date_and_time_l.setText("Date & Time                          :  ");

        Description_i_l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Description_i_l.setText("Description                            :");

        Location_l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Location_l.setText("Location                                :");

        CLAIM_DETAILS_L.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CLAIM_DETAILS_L.setText("Claim details :");

        Type_of_claim_l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Type_of_claim_l.setText("Type of claim                        :");

        Additionnal_comments_l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Additionnal_comments_l.setText("Additional comments         :");

        CANCEL.setActionCommand("CANCEL");
        CANCEL.setBackground(new java.awt.Color(0, 0, 0));
        CANCEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CANCEL.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        CANCEL.setForeground(new java.awt.Color(255, 255, 255));
        CANCEL.setLabel("CANCEL");
        CANCEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CANCELMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CANCELMouseExited(evt);
            }
        });
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });

        SUBMIT.setBackground(new java.awt.Color(0, 0, 0));
        SUBMIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SUBMIT.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        SUBMIT.setForeground(new java.awt.Color(255, 255, 255));
        SUBMIT.setLabel("SUBMIT");
        SUBMIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SUBMITMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SUBMITMouseExited(evt);
            }
        });
        SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITActionPerformed(evt);
            }
        });

        Additionnal_comments.setColumns(20);
        Additionnal_comments.setRows(5);
        jScrollPane5.setViewportView(Additionnal_comments);

        Type_of_claim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose claim", "Accident claim", "Theft claim", "Fire damage claim", "Natural calamity claim", "PIP(personal ingury protection) calim", "Vandalism claim", "Accidental death ", "Third-party accident" }));

        Description_i.setColumns(20);
        Description_i.setRows(5);
        jScrollPane2.setViewportView(Description_i);

        Location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose the location", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Andaman and Nicobar Islands", "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu", "Lakshadweep", "Delhi (National Capital Territory of Delhi)", "Puducherry", "Ladakh", "Lakshadweep" }));

        FIR_number_l1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FIR_number_l1.setText("FIR number                          :");

        verify.setBackground(new java.awt.Color(0, 51, 255));
        verify.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        verify.setForeground(new java.awt.Color(255, 255, 255));
        verify.setText("Verify");
        verify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verifyMouseExited(evt);
            }
        });
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });

        back_button_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previouspage.png"))); // NOI18N
        back_button_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_button_label)
                .addGap(284, 284, 284)
                .addComponent(CLAIMS_l)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Description_i_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(218, 218, 218))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CLAIM_DETAILS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Type_of_claim_l, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Additionnal_comments_l, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(SUBMIT, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 301, Short.MAX_VALUE)))
                        .addContainerGap(2, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Incident_details_l, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Location_l, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Date_and_time_l, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FIR_number_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Date_and_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)
                                    .addComponent(Type_of_claim, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Location, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FIR_number))
                                .addGap(18, 18, 18)
                                .addComponent(verify)))
                        .addGap(0, 211, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back_button_label)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CLAIMS_l, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Incident_details_l, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Date_and_time_l, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Location_l, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Date_and_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Description_i_l, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CLAIM_DETAILS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Type_of_claim_l, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Type_of_claim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FIR_number, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FIR_number_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verify))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Additionnal_comments_l, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SUBMIT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1148, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(75, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>                        

    private void CANCELMouseEntered(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        CANCEL.setBackground(new java.awt.Color(255, 0, 0));
        CANCEL.setForeground(new java.awt.Color(0, 0, 0));
    }                                   

    private void CANCELMouseExited(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
        CANCEL.setBackground(new java.awt.Color(0, 0, 0));
        CANCEL.setForeground(new java.awt.Color(255, 255, 255));
    }                                  

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {                                       
        new UserSelectClaimVehicle(CustomerID).setVisible(true);
        this.dispose();
    }                                      

    private void SUBMITMouseEntered(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        SUBMIT.setBackground(new java.awt.Color(0, 204, 0));
        SUBMIT.setForeground(new java.awt.Color(0, 0, 0));
    }                                   

    private void SUBMITMouseExited(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
        SUBMIT.setBackground(new java.awt.Color(0, 0, 0));
        SUBMIT.setForeground(new java.awt.Color(255, 255, 255));
    }                                  

    private void SUBMITActionPerformed(java.awt.event.ActionEvent evt) {                                       
        String firNumber = FIR_number.getText();
        java.util.Date incidentDate = Date_and_time.getDate();
        String incidentDescription = Description_i.getText();
        String location = (String) Location.getSelectedItem();
        String claimType = (String) Type_of_claim.getSelectedItem();
        String additionalComments = Additionnal_comments.getText();

        // Generate a random 6-digit claim ID
        // Random random = new Random();
        // int randomInt = 100000 + random.nextInt(900000);
        // String claimId = String.valueOf(randomInt);

        // Convert date to SQL date
        java.sql.Date sqlDate = new java.sql.Date(incidentDate.getTime());

        // Collect file paths of selected attachments

        // Insert the data into the database
        try(Connection conn = DBConnector.getConnection();) {
            
            String sql = "INSERT INTO Claim (date_time_of_incident,location,description,claim_type,claim_status,fir_number,registration_number,Policy_Number,additional_comments) VAULES (?,?,?,?,?,?,?,?,?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.setDate(1, sqlDate);
            pstmt.setString(2, location);
            pstmt.setString(3, incidentDescription);
            pstmt.setString(4, claimType);
            pstmt.setString(5, "Pending");
            pstmt.setString(6, firNumber);
            pstmt.setString(7, VehicleNumber);
            pstmt.setInt(8, getPolicyNumber(VehicleNumber));
            
            pstmt.setString(9, additionalComments);
            pstmt.executeUpdate();
            conn.close();

            // Show a success message
            JOptionPane.showMessageDialog(this, "Claim submitted successfully with Claim ID: " + getClaimID(VehicleNumber));
        } catch (SQLException e) {
            e.printStackTrace();
            // Show an error message
            JOptionPane.showMessageDialog(this, "Error submitting claim. Please try again.");
        }
    }                                      

    private int getPolicyNumber(String VehicleNumber){
        try(Connection conn = DBConnector.getConnection()){
            String query = "Select * from InsuredVehicle where Registration_Number = '" + VehicleNumber + "'";
            PreparedStatement statement = conn.prepareStatement(query);
            ResultSet result = statement.executeQuery();
            if(result.next()){
                return result.getInt("Policy_Number");
            }
        } catch(SQLException ex) {
            ex.printStackTrace();
        }
        return 0; 
    }
    private int getClaimID(String VehicleNumber){
        try(Connection conn = DBConnector.getConnection()){
            String query = "Select * from Claim where Registration_Number = '" + VehicleNumber + "'";
            PreparedStatement statement = conn.prepareStatement(query);
            ResultSet result = statement.executeQuery();
            if(result.next()){
                return result.getInt("claim_ID");
            }
        } catch(SQLException ex) {
            ex.printStackTrace();
        }
        return 0; 
    }
    private void verifyMouseEntered(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        verify.setForeground(new java.awt.Color(0, 0, 0));
    }                                   

    private void verifyMouseExited(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
        verify.setForeground(new java.awt.Color(255, 255, 255));
    }                                  

    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {                                       
        try (Connection conn = DBConnector.getConnection()){
            String query = "SELECCT * FROM FIR_Table WHERE FIR_Number = ? AND Vehicle_Number = ?";
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setInt(1, Integer.parseInt(FIR_number.getText()));
            statement.setString(2, VehicleNumber);
            ResultSet result = statement.executeQuery();

            if(result.next()){
                JOptionPane.showMessageDialog(this, "FIR is verifired","Verified",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid FIR!","Invalid",JOptionPane.ERROR_MESSAGE);
                FIR_number.setText("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }                                      

    private void back_button_labelMouseClicked(java.awt.event.MouseEvent evt) {                                               
        new UserSelectClaimVehicle(CustomerID).setVisible(true);
        this.dispose();
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClaimPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClaimPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClaimPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClaimPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClaimPolicy(0,"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea Additionnal_comments;
    private javax.swing.JLabel Additionnal_comments_l;
    private java.awt.Button CANCEL;
    private javax.swing.JLabel CLAIMS_l;
    private javax.swing.JLabel CLAIM_DETAILS_L;
    private com.toedter.calendar.JDateChooser Date_and_time;
    private javax.swing.JLabel Date_and_time_l;
    private javax.swing.JTextArea Description_i;
    private javax.swing.JLabel Description_i_l;
    private javax.swing.JTextField FIR_number;
    private javax.swing.JLabel FIR_number_l1;
    private javax.swing.JLabel Incident_details_l;
    private javax.swing.JLabel Location_l;
    private java.awt.Button SUBMIT;
    private javax.swing.JComboBox<String> Type_of_claim;
    private javax.swing.JComboBox<String> Location;
    private javax.swing.JLabel Type_of_claim_l;
    private javax.swing.JLabel back_button_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton verify;
    // End of variables declaration                   
}