package com.example;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vivek
 */
public class ClaimStatus extends javax.swing.JFrame {

    /**
     * Creates new form ClaimStatus
     */
    int CustomerID;
    public ClaimStatus(int CustomerID) {
        this.CustomerID = CustomerID;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        // this.setSize(900,550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Companyname_label = new javax.swing.JLabel();
        claim_status_header_panel = new javax.swing.JPanel();
        check_Claim_Status_label = new javax.swing.JLabel();
        claim_Entry_Panel = new javax.swing.JPanel();
        enter_claim_reg_label = new javax.swing.JLabel();
        claim_reg_no_inputtextfield = new javax.swing.JTextField();
        submit_Button = new javax.swing.JButton();
        back_Button = new javax.swing.JButton();
        table_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        claim_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        table_panel.setVisible(false);
        Companyname_label.setFont(new java.awt.Font("Optima", 1, 36)); // NOI18N
        Companyname_label.setForeground(new java.awt.Color(24, 116, 227));
        Companyname_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Companyname_label.setText("BMV Bazaar");
        Companyname_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Companyname_labelMouseClicked(evt);
            }
        });

        check_Claim_Status_label.setBackground(new java.awt.Color(69, 192, 255));
        check_Claim_Status_label.setFont(new java.awt.Font("Helvetica Neue", 2, 24)); // NOI18N
        check_Claim_Status_label.setForeground(new java.awt.Color(255, 255, 255));
        check_Claim_Status_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        check_Claim_Status_label.setText("Check Claim Status");
        check_Claim_Status_label.setOpaque(true);

        javax.swing.GroupLayout claim_status_header_panelLayout = new javax.swing.GroupLayout(claim_status_header_panel);
        claim_status_header_panel.setLayout(claim_status_header_panelLayout);
        claim_status_header_panelLayout.setHorizontalGroup(
            claim_status_header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(claim_status_header_panelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(check_Claim_Status_label, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        claim_status_header_panelLayout.setVerticalGroup(
            claim_status_header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(claim_status_header_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(check_Claim_Status_label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        enter_claim_reg_label.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        enter_claim_reg_label.setText("Enter Claim Registration Number:");

        claim_reg_no_inputtextfield.setText(" ");

        submit_Button.setBackground(new java.awt.Color(69, 192, 255));
        submit_Button.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        submit_Button.setForeground(new java.awt.Color(255, 255, 255));
        submit_Button.setText("Submit");
        submit_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_ButtonActionPerformed(evt);
            }
        });

        back_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previouspage.png"))); // NOI18N
        back_Button.setText(" ");
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout claim_Entry_PanelLayout = new javax.swing.GroupLayout(claim_Entry_Panel);
        claim_Entry_Panel.setLayout(claim_Entry_PanelLayout);
        claim_Entry_PanelLayout.setHorizontalGroup(
            claim_Entry_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(claim_Entry_PanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(claim_Entry_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(claim_Entry_PanelLayout.createSequentialGroup()
                        .addComponent(back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit_Button))
                    .addGroup(claim_Entry_PanelLayout.createSequentialGroup()
                        .addComponent(enter_claim_reg_label)
                        .addGap(18, 18, 18)
                        .addComponent(claim_reg_no_inputtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        claim_Entry_PanelLayout.setVerticalGroup(
            claim_Entry_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(claim_Entry_PanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(claim_Entry_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter_claim_reg_label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claim_reg_no_inputtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(claim_Entry_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_Button)
                    .addComponent(submit_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        claim_table.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        claim_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null,null}
            },
            new String [] {
                "Claim Registration Number", "Status", "Claim Date", "Policy number", "Insured Vehicle", "Claim Type", "Claim Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            // boolean[] canEdit = new boolean [] {
            //     false, false, false, false, false, false, false
            // };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            // public boolean isCellEditable(int rowIndex, int columnIndex) {
            //     return canEdit [columnIndex];
            // }
        });
        claim_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        claim_table.getColumnModel().getColumn(0).setPreferredWidth(180);
        claim_table.getColumnModel().getColumn(1).setPreferredWidth(90);
        claim_table.getColumnModel().getColumn(2).setPreferredWidth(190);
        claim_table.getColumnModel().getColumn(3).setPreferredWidth(160);
        claim_table.getColumnModel().getColumn(4).setPreferredWidth(170);
        claim_table.getColumnModel().getColumn(5).setPreferredWidth(120);
        claim_table.getColumnModel().getColumn(6).setPreferredWidth(90);
        claim_table.setRowHeight(45);
        claim_table.setRowMargin(5);
        claim_table.setShowGrid(true);
        jScrollPane1.setViewportView(claim_table);

        javax.swing.GroupLayout table_panelLayout = new javax.swing.GroupLayout(table_panel);
        table_panel.setLayout(table_panelLayout);
        table_panelLayout.setHorizontalGroup(
            table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        table_panelLayout.setVerticalGroup(
            table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, table_panelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(claim_Entry_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Companyname_label)
                        .addGap(18, 18, 18)
                        .addComponent(claim_status_header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(table_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(claim_status_header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Companyname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(claim_Entry_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(table_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt){
        this.dispose();
        new UserHomePage(CustomerID).setVisible(true);
    }
    private void submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        table_panel.setVisible(true);  
        String claim_no = claim_reg_no_inputtextfield.getText();                                          
        try(Connection conn = DBConnector.getConnection()){
            PreparedStatement statement = conn.prepareStatement("SELECT claim_ID,claim_status,date_time_of_incident,Policy_Number,registration_number,claim_type,claim_amount FROM Claim WHERE claim_ID = ?;");
            statement.setString(1, claim_no);
            ResultSet result = statement.executeQuery();
            if (result.next()){
                String claimRegNo = result.getString(1);
                String status = result.getString(2);
                String claimDate = result.getString(3);
                String policyNumber = result.getString(4);
                String insuredName = result.getString(5);
                String claimType = result.getString(6);
                String claimamt = result.getString(7) ;

                String[] rowData = {claimRegNo, status, claimDate, policyNumber, insuredName, claimType,claimamt};
                DefaultTableModel tblModel = (DefaultTableModel)claim_table.getModel();
                tblModel.removeRow(0);
                tblModel.addRow(rowData);
            }
            else {
                System.out.println("No data found for claim registration number"+ claim_no);
              }
        }catch (SQLException ex){ex.printStackTrace();}



        // String initialrowdata[]={"0","0","0","0","0","0"};
        // DefaultTableModel tblModel = (DefaultTableModel)claim_table.getModel();
        // tblModel.removeRow(0);
        // tblModel.addRow(initialrowdata);
    }                                          

    private void Companyname_labelMouseClicked(java.awt.event.MouseEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClaimStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClaimStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClaimStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClaimStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClaimStatus(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Companyname_label;
    private javax.swing.JButton back_Button;
    private javax.swing.JLabel check_Claim_Status_label;
    private javax.swing.JPanel claim_Entry_Panel;
    private javax.swing.JTextField claim_reg_no_inputtextfield;
    private javax.swing.JPanel claim_status_header_panel;
    private javax.swing.JTable claim_table;
    private javax.swing.JLabel enter_claim_reg_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submit_Button;
    private javax.swing.JPanel table_panel;
    // End of variables declaration                   
}
