package com.example;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Claims extends javax.swing.JFrame {

    /**
     * Creates new form Claims
     */
    public Claims() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        CLAIMS_l = new javax.swing.JLabel();
        Incident_details_l = new javax.swing.JLabel();
        Date_and_time_l = new javax.swing.JLabel();
        Description_i_l = new javax.swing.JLabel();
        Location_l = new javax.swing.JLabel();
        CLAIM_DETAILS_L = new javax.swing.JLabel();
        Type_of_claim_l = new javax.swing.JLabel();
        Description_c_l = new javax.swing.JLabel();
        Attachments_l = new javax.swing.JLabel();
        Additional_comments_l = new javax.swing.JLabel();
        CANCEL = new java.awt.Button();
        SUBMIT = new java.awt.Button();
        jScrollPane4 = new javax.swing.JScrollPane();
        Description_c = new javax.swing.JTextArea();
        Attachments = new javax.swing.JFileChooser();
        jScrollPane5 = new javax.swing.JScrollPane();
        Additional_comments = new javax.swing.JTextArea();
        Type_of_claim = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Description_i = new javax.swing.JTextArea();
        Date_and_time = new com.toedter.calendar.JDateChooser();
        Location = new javax.swing.JComboBox<>();
        FIR_number = new javax.swing.JTextField();
        FIR_number_l = new javax.swing.JLabel();
        verify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CLAIMS_l.setFont(new java.awt.Font("Arial", Font.BOLD, 24)); // NOI18N
        CLAIMS_l.setForeground(new java.awt.Color(0, 51, 255));
        CLAIMS_l.setText("CLAIMS");

        Incident_details_l.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 18)); // NOI18N
        Incident_details_l.setText("Incident details   :");

        Date_and_time_l.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        Date_and_time_l.setText("Date & Time                          :");

        Description_i_l.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        Description_i_l.setText("Description                            :");

        Location_l.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        Location_l.setText("Location                                :");

        CLAIM_DETAILS_L.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 18)); // NOI18N
        CLAIM_DETAILS_L.setText("Claim details :");

        Type_of_claim_l.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        Type_of_claim_l.setText("Type of claim                        :");

        Description_c_l.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        Description_c_l.setText("Description                            :");

        Attachments_l.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        Attachments_l.setText("Attachments                        :");

        Additional_comments_l.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        Additional_comments_l.setText("Additional comments         :");

        CANCEL.setActionCommand("CANCEL");
        CANCEL.setBackground(new java.awt.Color(0, 0, 0));
        CANCEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CANCEL.setFont(new java.awt.Font("Dialog", Font.BOLD, 12)); // NOI18N
        CANCEL.setForeground(new java.awt.Color(255, 255, 255));
        CANCEL.setLabel("CANCEL");
        CANCEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CANCELMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                CANCELMouseExited(evt);
            }
        });
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });

        SUBMIT.setBackground(new java.awt.Color(0, 0, 0));
        SUBMIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SUBMIT.setFont(new java.awt.Font("Dialog", Font.BOLD, 12)); // NOI18N
        SUBMIT.setForeground(new java.awt.Color(255, 255, 255));
        SUBMIT.setLabel("SUBMIT");
        SUBMIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SUBMITMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                SUBMITMouseExited(evt);
            }
        });
        SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITActionPerformed(evt);
            }
        });

        Description_c.setColumns(20);
        Description_c.setRows(5);
        jScrollPane4.setViewportView(Description_c);

        Attachments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachmentsActionPerformed(evt);
            }
        });

        Additional_comments.setColumns(20);
        Additional_comments.setRows(5);
        jScrollPane5.setViewportView(Additional_comments);

        Type_of_claim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Choose claim", "Accident claim", "Theft claim", "Fire damage claim", "Natural calamity claim", "PIP (personal injury protection) claim", "Vandalism claim", "Accidental death", "Third-party accident"}));

        Description_i.setColumns(20);
        Description_i.setRows(5);
        jScrollPane2.setViewportView(Description_i);

        Location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Choose the location", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Andaman and Nicobar Islands", "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu", "Lakshadweep", "Delhi (National Capital Territory of Delhi)", "Puducherry", "Ladakh", "Lakshadweep"}));

        FIR_number_l.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        FIR_number_l.setText("FIR number                          :");

        verify.setBackground(new java.awt.Color(0, 51, 255));
        verify.setFont(new java.awt.Font("Segoe UI Historic", Font.BOLD, 12)); // NOI18N
        verify.setForeground(new java.awt.Color(255, 255, 255));
        verify.setText("Verify");
        verify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verifyMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                verifyMouseExited(evt);
            }
        });
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CLAIM_DETAILS_L)
                                        .addComponent(Incident_details_l)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(Location_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Description_i_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Date_and_time_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(FIR_number_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(FIR_number)
                                                        .addComponent(Date_and_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                                                        .addComponent(Location, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(Attachments_l, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Description_c_l, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Type_of_claim_l, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Additional_comments_l, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(Type_of_claim, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(Attachments, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(287, 287, 287)
                                                .addComponent(CLAIMS_l)))
                                .addContainerGap(182, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(verify, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(SUBMIT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(197, 197, 197))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CLAIMS_l, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(Incident_details_l, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FIR_number_l, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FIR_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Date_and_time_l, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Date_and_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Description_i_l, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Location_l, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addComponent(CLAIM_DETAILS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Type_of_claim_l, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Type_of_claim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Description_c_l, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Attachments_l, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Attachments, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Additional_comments_l, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(SUBMIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(verify)))
                                .addGap(27, 27, 27))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void CANCELMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        CANCEL.setBackground(new java.awt.Color(255, 0, 0));
    }

    private void CANCELMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        CANCEL.setBackground(new java.awt.Color(0, 0, 0));
    }

    private void SUBMITMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        SUBMIT.setBackground(new java.awt.Color(0, 51, 204));
    }

    private void SUBMITMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        SUBMIT.setBackground(new java.awt.Color(0, 0, 0));
    }

    private void SUBMITActionPerformed(java.awt.event.ActionEvent evt) {
        // Retrieve data from the form
        String firNumber = FIR_number.getText();
        java.util.Date incidentDate = Date_and_time.getDate();
        String incidentDescription = Description_i.getText();
        String location = (String) Location.getSelectedItem();
        String claimType = (String) Type_of_claim.getSelectedItem();
        String claimDescription = Description_c.getText();
        String additionalComments = Additional_comments.getText();

        // Generate a random 6-digit claim ID
        Random random = new Random();
        int randomInt = 100000 + random.nextInt(900000);
        String claimId = String.valueOf(randomInt);

        // Convert date to SQL date
        java.sql.Date sqlDate = new java.sql.Date(incidentDate.getTime());

        // Collect file paths of selected attachments
        File[] selectedFiles = Attachments.getSelectedFiles();
        StringBuilder attachmentsBuilder = new StringBuilder();
        for (File file : selectedFiles) {
            attachmentsBuilder.append(file.getAbsolutePath()).append(";");
        }
        String attachments = attachmentsBuilder.toString();

        // Insert the data into the database
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/claims_db", "username", "password");
            String sql = "INSERT INTO claims (claim_id, incident_description, claim_description, fir_number, incident_date, claim_type, location, additional_comments, attachments) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, claimId);
            pstmt.setString(2, incidentDescription);
            pstmt.setString(3, claimDescription);
            pstmt.setString(4, firNumber);
            pstmt.setDate(5, sqlDate);
            pstmt.setString(6, claimType);
            pstmt.setString(7, location);
            pstmt.setString(8, additionalComments);
            pstmt.setString(9, attachments);
            pstmt.executeUpdate();
            conn.close();

            // Show a success message
            JOptionPane.showMessageDialog(this, "Claim submitted successfully with Claim ID: " + claimId);
        } catch (SQLException e) {
            e.printStackTrace();
            // Show an error message
            JOptionPane.showMessageDialog(this, "Error submitting claim. Please try again.");
        }
    }

    private void AttachmentsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void verifyMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void verifyMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        // Verification logic goes here
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Claims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Claims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Claims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Claims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Claims().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private JTextArea Additional_comments;
    private javax.swing.JLabel Additional_comments_l;
    private javax.swing.JFileChooser Attachments;
    private javax.swing.JLabel Attachments_l;
    private javax.swing.JLabel CLAIMS_l;
    private javax.swing.JLabel CLAIM_DETAILS_L;
    private java.awt.Button CANCEL;
    private com.toedter.calendar.JDateChooser Date_and_time;
    private javax.swing.JLabel Date_and_time_l;
    private javax.swing.JTextArea Description_c;
    private javax.swing.JLabel Description_c_l;
    private javax.swing.JTextArea Description_i;
    private javax.swing.JLabel Description_i_l;
    private javax.swing.JTextField FIR_number;
    private javax.swing.JLabel FIR_number_l;
    private javax.swing.JLabel Incident_details_l;
    private javax.swing.JComboBox<String> Location;
    private javax.swing.JLabel Location_l;
    private java.awt.Button SUBMIT;
    private javax.swing.JComboBox<String> Type_of_claim;
    private javax.swing.JLabel Type_of_claim_l;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton verify;
    // End of variables declaration
}