package com.example;

import javax.swing.JOptionPane;

import com.mysql.cj.protocol.Resultset;

import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseAdapter;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vivek
 */
public class PolicyPage extends javax.swing.JFrame {

    /**
     * Creates new form policypage
     */
    String VehicleNumber,Vtype;
    public PolicyPage(String VehicleNumber,String Vtype) {
        this.VehicleNumber = VehicleNumber;
        this. Vtype = Vtype;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        navigateToRecord(Vtype);
        // navigateToRecord("Bike");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Companyname_label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        available_plans_Label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        insurancename_pic_label = new javax.swing.JLabel();
        Policyprice_label = new javax.swing.JLabel();
        maxcoverage_Label = new javax.swing.JLabel();
        maxcoverage_price = new javax.swing.JLabel();
        claims_settled_label = new javax.swing.JLabel();
        claims_settled_percent_label = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        previous_page_label = new javax.swing.JLabel();
        next_page_label = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Companyname_label.setFont(new java.awt.Font("Optima", 1, 36)); // NOI18N
        Companyname_label.setForeground(new java.awt.Color(24, 116, 227));
        Companyname_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Companyname_label.setText("BMV Bazaar");
        Companyname_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Companyname_label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                Companyname_labelMouseClicked();
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Companyname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(Companyname_label)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        available_plans_Label.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        available_plans_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        available_plans_Label.setText("Available Plans for You:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(available_plans_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(available_plans_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        // insurancename_pic_label.setText("Logo");
        // insurancename_pic_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reliance.png")));

        Policyprice_label.setBackground(new java.awt.Color(69, 192, 255));
        Policyprice_label.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Policyprice_label.setForeground(new java.awt.Color(255, 255, 255));
        Policyprice_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Policyprice_label.setText("Price");
        Policyprice_label.setOpaque(true);

        maxcoverage_Label.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        maxcoverage_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxcoverage_Label.setText("Max Coverage:");

        maxcoverage_price.setBackground(new java.awt.Color(184, 175, 255));
        maxcoverage_price.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        maxcoverage_price.setForeground(new java.awt.Color(255, 255, 255));
        maxcoverage_price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxcoverage_price.setText("Max_Price");
        maxcoverage_price.setOpaque(true);

        claims_settled_label.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        claims_settled_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        claims_settled_label.setText("Claims Settled:");

        claims_settled_percent_label.setText("claims_settled_percent");
        claims_settled_percent_label.setFont(new Font("Helvetica Neue", 1, 18));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(claims_settled_label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(claims_settled_percent_label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(Policyprice_label, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(insurancename_pic_label, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maxcoverage_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(maxcoverage_price, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insurancename_pic_label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxcoverage_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxcoverage_price, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Policyprice_label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claims_settled_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claims_settled_percent_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        previous_page_label.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        previous_page_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previouspage.png"))); // NOI18N
        previous_page_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previous_page_label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                try {
                    if(result.previous()){
                        displayRecord();
                    } else {
                        result.last();
                        displayRecord();
                    }
                } catch (SQLException e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                }
            }
        });

        next_page_label.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        next_page_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nextpage.png"))); // NOI18N
        next_page_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next_page_label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                try {
                    if(result.next()){
                        displayRecord();
                    } else {
                        result.first();
                        displayRecord();
                    }
                } catch (SQLException e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                }
            }
        });

        submitButton.setBackground(new java.awt.Color(0, 0, 0));
        submitButton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Proceed");
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    submitButtonActionPerformed(evt);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(previous_page_label)
                .addGap(33, 33, 33)
                .addComponent(next_page_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(previous_page_label))
                    .addComponent(next_page_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>                        

    private void navigateToRecord(String type) {
        try{
            Connection conn = DBConnector.getConnection();
            PreparedStatement statement = conn.prepareStatement("SELECT * from List_of_Policies WHERE VehicleType = ?",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            statement.setString(1, type);
            result = statement.executeQuery();
            
            if(result.next()){
                displayRecord();
            }
        } catch(SQLException ex){
            ex.printStackTrace();
        }
    }
    private void displayRecord() throws SQLException{
        claims_settled_percent_label.setText(result.getString("ClaimsSettled"));
        // insurancename_pic_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+result.getString("Provider")+".png")));
        insurancename_pic_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+result.getString("Provider")+".gif.png")));
        maxcoverage_price.setText(Double.toString(getMaxCoverage(VehicleNumber)));  // casting double to string
        Policyprice_label.setText(Double.toString(getPremium(VehicleNumber)));
        
    }
    private double getMaxCoverage(String VehicleNumber){
        try(Connection conn = DBConnector.getConnection()){
            String query = "SELECT * FROM Vehicle_Details WHERE registration_number = '" + VehicleNumber +"'";
            PreparedStatement statement = conn.prepareStatement(query);
            ResultSet rs = statement.executeQuery();
            if(rs.next()){
                return MaxCoverageCalculator.calculateMaxCoverage(rs.getInt("year"),result.getDouble("Max_Coverage_Constant"),Vtype);
            } else {
                JOptionPane.showMessageDialog(this, "No vehicle found","",JOptionPane.ERROR_MESSAGE);
                return -1;
            }
        } catch (SQLException ex){
            ex.printStackTrace();
            return -1;
        }
    }
    private double getPremium(String VehicleNumber){
        try(Connection conn = DBConnector.getConnection()){
            String query = "SELECT * FROM Vehicle_Details WHERE registration_number = '" + VehicleNumber +"'";
            PreparedStatement statement = conn.prepareStatement(query);
            ResultSet rs = statement.executeQuery();
            if(rs.next()){
                return PolicyPremiumCalculator.calculatePolicyPremium(rs.getInt("year"),result.getDouble("Max_Coverage_Constant"),Vtype);
            } else {
                JOptionPane.showMessageDialog(this, "No vehicle found","",JOptionPane.ERROR_MESSAGE);
                return -1;
            }
        } catch (SQLException ex){
            ex.printStackTrace();
            return -1;
        }
    }
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {       
        int PolicyID = result.getInt("PolicyID");    
                                          
        new PolicyInfo(PolicyID,VehicleNumber,PolicyPremiumCalculator.getPremiuim_UsingPolicyID(PolicyID, VehicleNumber)).setVisible(true);
        this.setVisible(false);
    }                                            
    private void Companyname_labelMouseClicked(){
        this.dispose();
        new UserHomePage(DBConnector.getCustomerID_UsingVehicleNumber(VehicleNumber));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolicyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolicyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolicyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolicyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolicyPage("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Companyname_label;
    private javax.swing.JLabel Policyprice_label;
    private javax.swing.JLabel available_plans_Label;
    private javax.swing.JLabel claims_settled_label;
    private javax.swing.JLabel claims_settled_percent_label;
    private javax.swing.JLabel insurancename_pic_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel maxcoverage_Label;
    private javax.swing.JLabel maxcoverage_price;
    private javax.swing.JLabel next_page_label;
    private javax.swing.JLabel previous_page_label;
    private javax.swing.JButton submitButton;
    private ResultSet result;
    // End of variables declaration                   
}