package com.example;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import com.mysql.cj.xdevapi.PreparableStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vivek
 */
public class PolicyInfo extends javax.swing.JFrame {

    /**
     * Creates new form PolicyInfo
     */
    private int PolicyID;
    public PolicyInfo(int PID) {
        this.PolicyID = PID;
        // this.PolicyID = 1;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        Companyname_label = new javax.swing.JLabel();
        info_Panel = new javax.swing.JPanel();
        highlights_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        highlights_TextArea = new javax.swing.JTextArea();
        exclusion_Label = new javax.swing.JLabel();
        claim_Label = new javax.swing.JLabel();
        confirm_purchase_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Companyname_label.setFont(new java.awt.Font("Optima", 1, 36)); // NOI18N
        Companyname_label.setForeground(new java.awt.Color(24, 116, 227));
        Companyname_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Companyname_label.setText("BMV Bazaar");
        Companyname_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Companyname_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Companyname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(Companyname_label)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        highlights_Label.setBackground(new java.awt.Color(24, 116, 227));
        highlights_Label.setFont(new java.awt.Font("Gill Sans", 2, 24)); // NOI18N
        highlights_Label.setForeground(new java.awt.Color(255, 255, 255));
        highlights_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highlights_Label.setText("Highlights");
        highlights_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        highlights_Label.setOpaque(true);
        highlights_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                highlights_LabelMouseClicked(evt);
            }
        });

        highlights_TextArea.setEditable(false);
        highlights_TextArea.setColumns(20);
        highlights_TextArea.setLineWrap(true);
        highlights_TextArea.setRows(5);
        highlights_TextArea.setWrapStyleWord(true);
        highlights_TextArea.setFont(new java.awt.Font("Gill Sans",2,15));
        jScrollPane1.setViewportView(highlights_TextArea);

        exclusion_Label.setBackground(new java.awt.Color(24, 116, 227));
        exclusion_Label.setFont(new java.awt.Font("Gill Sans", 2, 24)); // NOI18N
        exclusion_Label.setForeground(new java.awt.Color(255, 255, 255));
        exclusion_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); 
        exclusion_Label.setText("Exclusions");
        exclusion_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exclusion_Label.setOpaque(true);
        exclusion_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exclusion_LabelMouseClicked(evt);
            }
        });

        claim_Label.setBackground(new java.awt.Color(24, 116, 227));
        claim_Label.setFont(new java.awt.Font("Gill Sans", 2, 24)); // NOI18N
        claim_Label.setForeground(new java.awt.Color(255, 255, 255));
        claim_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        claim_Label.setText("Claim Procedure");
        claim_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        claim_Label.setOpaque(true);
        claim_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                claim_LabelMouseClicked(evt);
            }
        });

        confirm_purchase_Button.setBackground(new java.awt.Color(0, 0, 0));
        confirm_purchase_Button.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        confirm_purchase_Button.setForeground(new java.awt.Color(255, 255, 255));
        confirm_purchase_Button.setText("Confirm Purchase");
        confirm_purchase_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirm_purchase_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_purchase_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout info_PanelLayout = new javax.swing.GroupLayout(info_Panel);
        info_Panel.setLayout(info_PanelLayout);
        info_PanelLayout.setHorizontalGroup(
            info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_PanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(info_PanelLayout.createSequentialGroup()
                .addGroup(info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info_PanelLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(highlights_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exclusion_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(claim_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(info_PanelLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(confirm_purchase_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        info_PanelLayout.setVerticalGroup(
            info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_PanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(highlights_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exclusion_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claim_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirm_purchase_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(info_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(info_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void confirm_purchase_ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        this.dispose();
        new checkout("",0,0).setVisible(true);
    }                                                       

    private void Companyname_labelMouseClicked(java.awt.event.MouseEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void highlights_LabelMouseClicked(java.awt.event.MouseEvent evt) {                                              
            displayDetails(PolicyID,"Highlights");
    }                                             

    private void exclusion_LabelMouseClicked(java.awt.event.MouseEvent evt) {                                             
        displayDetails(PolicyID,"Exclusions");

    }                                            

    private void claim_LabelMouseClicked(java.awt.event.MouseEvent evt) {                                         
        displayDetails(PolicyID,"ClaimProcedure");

    }                                        
    private void displayDetails(int PolicyID,String column){
        try(Connection conn = DBConnector.getConnection()){
            String query = "SELECT * FROM List_of_Policies WHERE PolicyID = ?";
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setInt(1, PolicyID);

            result = statement.executeQuery();
            result.next();
            highlights_TextArea.setText("");
            try {
                String policyDetails = retrievePolicyDetails(PolicyID,column);
                List<String> sentences = splitIntoSentences(policyDetails);
                for (String sentence : sentences) {
                    highlights_TextArea.append(sentence + ".\n"); // Append each sentence with a new line
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (SQLException ex){
            ex.printStackTrace();
        }
    }
    public static String retrievePolicyDetails(int PID,String column) throws SQLException {
        String policyDetails = "";

        try (Connection connection = DBConnector.getConnection()){
            PreparedStatement statement = connection.prepareStatement("SELECT * FROM List_of_Policies WHERE PolicyID = ?");
            statement.setInt(1, PID); // Set your desired PolicyID
            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                policyDetails = resultSet.getString(column);
            }
        }

        return policyDetails;
    }
    public static List<String> splitIntoSentences(String text) {
    List<String> sentences = new ArrayList<>();
    String[] splitSentences = text.split("\\.");
    for (String sentence : splitSentences) {
        sentences.add(sentence.trim());
    }
    return sentences;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolicyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolicyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolicyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolicyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolicyInfo(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Companyname_label;
    private javax.swing.JLabel claim_Label;
    private javax.swing.JButton confirm_purchase_Button;
    private javax.swing.JLabel exclusion_Label;
    private javax.swing.JLabel highlights_Label;
    private javax.swing.JTextArea highlights_TextArea;
    private javax.swing.JPanel info_Panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private ResultSet result;
    // End of variables declaration                   
}
